---
name: Release Belug-Apps (Post Merge)
on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.base_ref == 'main'
    outputs:
      release_version: ${{ steps.semver.outputs.next }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          # NOTE: fetch all commits and tags
          fetch-depth: "0"

      - uses: asdf-vm/actions/setup@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0
      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
        with:
          path: ${{ env.ASDF_DIR }}
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-
      - uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0

      - name: Bump version to the next pre-release
        id: semver
        run: |
          tag="$(git tag --list | sort --version-sort --reverse | head --lines=1)"

          # NOTE: if no RC are found, we will create a new one based on the next minor
          #       release
          grep -- '-rc' <<<"${tag}" > /dev/null || tag="$(semver bump minor "${tag}")"

          echo >> "${GITHUB_OUTPUT}" "next=$(semver bump prerel rc.. "${tag}")"


  release:
    uses: ./.github/workflows/release.workflow.yml
    needs: [bump_version]
    with:
      version: ${{ needs.bump_version.outputs.release_version }}
      ref: main
      dryRun: false
    secrets: inherit
